### PR TITLE
Making 3rd TS the sample of interest

### PR DESCRIPTION
**Pull request by GNiramay**
Out of the 5 time samples that the QIE analyzes per event, we wish to consider the third time sample as the sample of interest. As a result, the `TrigScintRecHitProducer`  will reconstruct deposited energy from the ADCs received in the 3rd and 4th time sample.

### CODE REVIEW

**Comment by GNiramay** [comment]
A quick correction. The commit message for the latest commit says "Making 2nd TS the sample of interest". This was a typo. This whole PR is intended to make the third time sample, the sample of interest.

**Comment by bryngemark** [comment]
This looks unintrusive enough, but just a thought: is there any point in making the sample of interest a configurable variable instead of hardwiring it?

**Comment by GNiramay** [comment]
> This looks unintrusive enough, but just a thought: is there any point in making the sample of interest a configurable variable instead of hardwiring it? 

I guess it can be made configurable for now, just to play around. But in the bigger picture, we don't want to touch it. We want to keep it fixed.

**Comment by bryngemark** [comment]
> > This looks unintrusive enough, but just a thought: is there any point in making the sample of interest a configurable variable instead of hardwiring it?
> 
> I guess it can be made configurable for now, just to play around. But in the bigger picture, we don't want to touch it. We want to keep it fixed.

Sure enough, this is a phase. I think it's just my overall philosophy to make all arbitrary (or choice-driven) parameters configurable as far as possible, just because it reduces the need for both recompiling and making merge requests 😄

**Comment by GNiramay** [comment]
Now I have made the sample of interest configurable. Currently, it can be varied between 0,1,2,3.

**Review by bryngemark — APPROVED** [review]
This all looks good to me!

**Pull request merged**
