### PR TITLE
Tweaks to make simulation reconstruction closer to data 

### LINKED ISSUE #21: make digi producer less verbose
I suggest the printout level here gets reduced from `info` to `debug` since it happens on (every sim) hit level rather then a few-events level or at the start/end of process, or similar.

alternatively, add an extra qualifier using the producer's own `verbose` parameter.

https://github.com/LDMX-Software/TrigScint/blob/5b210429691b1b91c5c77bdacad85ccc980a1e90/src/TrigScint/TrigScintQIEDigiProducer.cxx#L97

### LINKED ISSUE #41: Make rechit producer more versatile to make data/MC comparisons easier
We want to compare testbeam data to simulations. Currently, the rechit producer used in the sim+digi chain has a hardwired number of time samples it integrates over, has a zero-suppression that has a fixed cut-off, etc. 

What's needed is summing signal over a configurable number of time samples, and a few other things, to get the shot noise (single PEs) properly simulated.

### PR DESCRIPTION
**Pull request by bryngemark**
This PR includes making hit reconstruction integrate over the full number of time samples, and a few minor bug fixes such as correct pedestal subtraction and zero suppression.

Also it reduces the QIEDigi verbosity which was an old issue. 

Closes #41 and closes #21 .

### CODE REVIEW

**Review by tomeichlersmith — APPROVED** [review]
Looks good from my POV.

**Review by GNiramay — APPROVED** [review]
Looks good to me.

**Comment by bryngemark** [comment]
I have now added in functionality that will also take care of event cleaning. So, also closes #43

**Comment by bryngemark** [comment]
@awhitbeck, is there anything else you'd like to see or can we have this merged? You have to approve in that case.

**Review by awhitbeck — APPROVED** [review]

**Pull request merged**
